### PR TITLE
Merge Develop

### PR DESCRIPTION
**Pull request by Olanetsoft**

### CODE REVIEW

**Review by blewater — COMMENTED** [review]
- Nice, is there a Url where I can view a demo site of this?
- Is it possible to offer any tests, like checking if the pages don't break with new changes?
- @Olanetsoft, it's not a good practice to create PR and approve them yourself. Either commit directly to the Main in the early phases of the project or even better accumulate a large documentation PR and then ask for a review/merge.

**Comment by Olanetsoft** [comment]
Thanks for your feedback @blewater 

1. I intentionally merged it because its the base commit
2. This is the original PR https://github.com/mara-labs/chain-docs/pull/2, and it was merged to the `develop` branch, not the main. I merged to the main from develop branch because it's the base commit. As the issue reflects `Project setup and config`.
3. You deleted the develop branch; not sure why but it will be best to have a staging branch to test out(serving as dev) before merging to main, where it goes public.
4. For test cases and workflow, a new issue will be added + a PR when it's ready.
5. For a URL to view live, I will need to fork the project and send PR from there so I can host it for the test. 

Another reason why we needed the `develop` branch is to host it as staging-docs.mara.xyz or staging.docs.mara.xyz which will serve as a pre-host before going live. All team members can view what is available on staging and do some QA test.

**Comment by blewater** [comment]
@Olanetsoft Sorry for deleting develop as part of the PR cleanup. Feel free to restore the `develop` branch from your local repo.

**Comment by blewater** [comment]
It's fine if you want to use a gitflow branching strategy where you commit all your work to develop and then to master.

**Comment by Olanetsoft** [comment]
No worries @blewater 

I wanted to do some cleaning up, but it seems I need the right access to this project or organization.

I can't restore the branch deleted, and when i created another one after forking the project, it wasn't reflected in the fork project. I think this has to do with some access privilege, i will be glad if that can be granted or if you help create a `develop` branch from the `main` branch.

**Pull request merged**
